FROM rocker/rstudio:latest

# Set arguments for R and package version.

RUN apt-get update -y \
  & apt-get install -y \
      build-essential \
      cmake \
  & R -e 'install.packages(c("arrow", "aws.s3", "data.table", "tidyverse", "dplyr", "tidyr", "odbc", "DBI", "purrr"))'
