# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_args_c <- function(x, argS, argL) {
    .Call(`_cmdline_arguments_find_args_c`, x, argS, argL)
}

find_args_single_c <- function(x, arg) {
    .Call(`_cmdline_arguments_find_args_single_c`, x, arg)
}

substring_c <- function(x, l) {
    .Call(`_cmdline_arguments_substring_c`, x, l)
}

match_args_c <- function(cmdArgs, cmdArgsPositions, cmdArgsNextPositions, parserArgs, parserArgsOrder, parserArgsRequired, helpArg) {
    .Call(`_cmdline_arguments_match_args_c`, cmdArgs, cmdArgsPositions, cmdArgsNextPositions, parserArgs, parserArgsOrder, parserArgsRequired, helpArg)
}

